version: '3.9'

services:
  web:
    container_name: ex-subdomain-web
    image: nginx:$NGINX_TAG
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./src:/var/www/html
      - ./log/nginx:/var/log/nginx
      # step1 default-80.conf.template 
      # step2 default-ssl.conf.template + $DOMAIN.crt, $DOMAIN.key
      - ./build/nginx/templates/default-80.conf.template:/etc/nginx/templates/default.conf.template
      # - ./build/nginx/templates/default-ssl.conf.template:/etc/nginx/templates/default.conf.template
      # - $CERT_PATH/live/$DOMAIN/fullchain.pem:/etc/letsencrypt/$DOMAIN.crt
      # - $CERT_PATH/live/$DOMAIN/privkey.pem:/etc/letsencrypt/$DOMAIN.key
    environment:
      # step1 first value is only VIRTUAL_HOST, VIRTUAL_PORT=80 .
      # step2 after creating certifications, add to VIRTUAL_PORT=443, HTTPS_METHOD, CERT_NAME. 
      - VIRTUAL_HOST=$DOMAIN
      - VIRTUAL_PORT=80
      # - VIRTUAL_PORT=443
      # - VIRTUAL_PROTO=https
      # - HTTPS_METHOD=noredirect
      # - CERT_NAME=$DOMAIN
      - NGINX_HOST=$DOMAIN
      - NGINX_PORT=443
    expose:
      - '80'
      - '443'
    networks:
      - default
      - proxy_default
  
  app:
    container_name: ex-subdomain-app
    image: php:$PHP_TAG
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./src:/var/www/html
      - ./build/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./build/php/php.ini:/usr/local/etc/php/php.ini
      - ./build/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    expose:
      - '9000'
    networks:
      - default
      - proxy_default

  cert:
    container_name: sl-webapp-cert
    image: certbot/certbot:$CERTBOT_TAG
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./src:/var/www/html
    command: ["--version"]
    
networks:
  default:
  proxy_default:
    external: true
