version: "3.3"

services:
  proxy:
    container_name: proxy
    image: jwilder/nginx-proxy:$PROXY_TAG
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default

networks:
  default:
    external: true
